services:
  dev:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.dev
    container_name: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    stdin_open: true

  prod:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.prod
    container_name: production
    ports:
      - "3001:3001"